export type Category = "All" | "Getting Started" | "Clips & AI" | "Exporting" | "Growth Tips" | "Advanced";

export interface Tutorial {
  id: string;
  title: string;
  desc: string;
  duration: string;
  level: "Beginner" | "Intermediate" | "Advanced";
  category: Exclude<Category, "All">;
  youtubeId: string;
  views?: string;
  new?: boolean;
}

export const TUTORIALS: Tutorial[] = [
  {
    id: "1",
    title: "Getting started with AutoClipr in 5 minutes",
    desc: "Create your account, connect your YouTube channel, and generate your first viral clip — all in under 5 minutes.",
    duration: "5:12",
    level: "Beginner",
    category: "Getting Started",
    youtubeId: "LmxTVsJfInQ",
    views: "12.4K",
    new: true,
  },
  {
    id: "2",
    title: "How to paste a YouTube URL and clip it",
    desc: "The fastest way to turn any YouTube video into short-form clips without any manual editing.",
    duration: "3:45",
    level: "Beginner",
    category: "Getting Started",
    youtubeId: "mXTlAKm0VEo",
    views: "9.1K",
  },
  {
    id: "3",
    title: "Understanding viral score — what the AI looks for",
    desc: "Deep dive into how AutoClipr scores moments and why some clips get flagged as high-potential.",
    duration: "7:30",
    level: "Intermediate",
    category: "Clips & AI",
    youtubeId: "Ypbsei0ug7w",
    views: "6.8K",
  },
  {
    id: "4",
    title: "Auto captions — customise style, font & colour",
    desc: "Make your clips stand out with perfectly styled captions. Learn every caption setting in AutoClipr.",
    duration: "6:10",
    level: "Beginner",
    category: "Clips & AI",
    youtubeId: "aiQrLxzu9ug",
    views: "8.3K",
  },
  {
    id: "5",
    title: "Export for TikTok, Reels & Shorts — best settings",
    desc: "The exact export settings to maximise quality and reach on every short-form platform.",
    duration: "4:55",
    level: "Beginner",
    category: "Exporting",
    youtubeId: "LmxTVsJfInQ",
    views: "11.2K",
  },
  {
    id: "6",
    title: "Batch export — process 10 clips at once",
    desc: "Save hours by queuing up multiple clips and exporting them all at once with one click.",
    duration: "3:20",
    level: "Intermediate",
    category: "Exporting",
    youtubeId: "mXTlAKm0VEo",
    views: "5.4K",
  },
  {
    id: "7",
    title: "How to post clips consistently without burning out",
    desc: "A practical system for turning one long video into a week of short-form content automatically.",
    duration: "8:45",
    level: "Beginner",
    category: "Growth Tips",
    youtubeId: "Ypbsei0ug7w",
    views: "14.7K",
    new: true,
  },
  {
    id: "8",
    title: "Which clips go viral — a data-driven breakdown",
    desc: "We analysed 10,000 clips generated by AutoClipr. Here is exactly what the top performers had in common.",
    duration: "11:20",
    level: "Intermediate",
    category: "Growth Tips",
    youtubeId: "aiQrLxzu9ug",
    views: "19.3K",
  },
  {
    id: "9",
    title: "Channel monitoring — auto-detect new uploads",
    desc: "Set up AutoClipr to automatically watch any YouTube channel and clip every new upload the moment it goes live.",
    duration: "5:50",
    level: "Advanced",
    category: "Advanced",
    youtubeId: "LmxTVsJfInQ",
    views: "4.2K",
  },
  {
    id: "10",
    title: "API access — automate everything with webhooks",
    desc: "For power users: use the AutoClipr API to trigger clip generation from your own tools and workflows.",
    duration: "14:05",
    level: "Advanced",
    category: "Advanced",
    youtubeId: "mXTlAKm0VEo",
    views: "3.1K",
  },
  {
    id: "11",
    title: "Niche-specific templates — gaming, fitness, finance",
    desc: "Use pre-built clip templates optimised for your niche. Each template uses platform-specific hooks and pacing.",
    duration: "6:35",
    level: "Intermediate",
    category: "Clips & AI",
    youtubeId: "Ypbsei0ug7w",
    views: "7.6K",
  },
  {
    id: "12",
    title: "Credits explained — how to get the most from your plan",
    desc: "Understand exactly how credits are deducted and the strategies to maximise your monthly clip quota.",
    duration: "4:00",
    level: "Beginner",
    category: "Getting Started",
    youtubeId: "aiQrLxzu9ug",
    views: "6.0K",
  },
];
